{
 "title": "Energy",
 "time": { "from": "2022-04-17T12:07:57.614Z", "to": "2022-04-17T14:24:55.214Z" },
 "panels": [
  {
   "title": "24h consumption in kWh",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(shelly_plug_energy_consumption_total[24h]))"
    }
   ]
  },
  {
   "title": "24h cost in euro",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(shelly_plug_energy_consumption_total[24h]))*0.25"
    }
   ]
  },
  {
   "title": "Total costs in Euro",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(shelly_plug_energy_consumption_total)*0.000017*0.25",
     "legendFormat": "Euro"
    }
   ]
  },
  {
   "title": "Projected cost per year in euro",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(shelly_plug_energy_consumption_total[24h]))*0.25*365"
    }
   ]
  },
  {
   "title": "Device temperatur in °C",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "shelly_plug_device_temperature" }
   ]
  },
  {
   "title": "Total Power consumption in kWh",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(shelly_plug_energy_consumption_total)*0.000017",
     "legendFormat": "kWh"
    }
   ]
  },
  {
   "title": "Average energy consumption in watt minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(shelly_plug_energy_consumption_total[1m])"
    }
   ]
  },
  {
   "title": "Current power consumption in watts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(shelly_plug_current_energy_consumption)"
    }
   ]
  },
  {
   "title": "Power consumption in watts  per device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "shelly_plug_current_energy_consumption"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}